// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes       = "BasicAuth.Scopes"
	PasetoAuthScopes      = "PasetoAuth.Scopes"
	PasetoQueryAuthScopes = "PasetoQueryAuth.Scopes"
)

// Defines values for AnalysisDataFormsLoginFormDetailsMethod.
const (
	AnalysisDataFormsLoginFormDetailsMethodPOST AnalysisDataFormsLoginFormDetailsMethod = "POST"
)

// Defines values for AnalysisErrorStatus.
const (
	AnalysisErrorStatusFailed AnalysisErrorStatus = "failed"
)

// Defines values for AnalysisInProgressStatus.
const (
	InProgress AnalysisInProgressStatus = "in_progress"
)

// Defines values for AnalysisResponseStatus.
const (
	AnalysisResponseStatusCompleted  AnalysisResponseStatus = "completed"
	AnalysisResponseStatusFailed     AnalysisResponseStatus = "failed"
	AnalysisResponseStatusInProgress AnalysisResponseStatus = "in_progress"
	AnalysisResponseStatusRequested  AnalysisResponseStatus = "requested"
)

// Defines values for AnalysisResultResultsFormsLoginFormDetailsMethod.
const (
	AnalysisResultResultsFormsLoginFormDetailsMethodPOST AnalysisResultResultsFormsLoginFormDetailsMethod = "POST"
)

// Defines values for AnalysisResultStatus.
const (
	Completed AnalysisResultStatus = "completed"
)

// Defines values for CacheDependencyCheckStatus.
const (
	CacheDependencyCheckStatusDegraded  CacheDependencyCheckStatus = "degraded"
	CacheDependencyCheckStatusHealthy   CacheDependencyCheckStatus = "healthy"
	CacheDependencyCheckStatusUnhealthy CacheDependencyCheckStatus = "unhealthy"
	CacheDependencyCheckStatusUnknown   CacheDependencyCheckStatus = "unknown"
)

// Defines values for DependencyCheckStatus.
const (
	DependencyCheckStatusDegraded  DependencyCheckStatus = "degraded"
	DependencyCheckStatusHealthy   DependencyCheckStatus = "healthy"
	DependencyCheckStatusUnhealthy DependencyCheckStatus = "unhealthy"
	DependencyCheckStatusUnknown   DependencyCheckStatus = "unknown"
)

// Defines values for FormAnalysisLoginFormDetailsMethod.
const (
	FormAnalysisLoginFormDetailsMethodPOST FormAnalysisLoginFormDetailsMethod = "POST"
)

// Defines values for HealthResponseChecksStatus.
const (
	HealthResponseChecksStatusDegraded  HealthResponseChecksStatus = "degraded"
	HealthResponseChecksStatusHealthy   HealthResponseChecksStatus = "healthy"
	HealthResponseChecksStatusUnhealthy HealthResponseChecksStatus = "unhealthy"
	HealthResponseChecksStatusUnknown   HealthResponseChecksStatus = "unknown"
)

// Defines values for HealthResponseChecksCacheStatus.
const (
	HealthResponseChecksCacheStatusDegraded  HealthResponseChecksCacheStatus = "degraded"
	HealthResponseChecksCacheStatusHealthy   HealthResponseChecksCacheStatus = "healthy"
	HealthResponseChecksCacheStatusUnhealthy HealthResponseChecksCacheStatus = "unhealthy"
	HealthResponseChecksCacheStatusUnknown   HealthResponseChecksCacheStatus = "unknown"
)

// Defines values for HealthResponseChecksQueueStatus.
const (
	HealthResponseChecksQueueStatusDegraded  HealthResponseChecksQueueStatus = "degraded"
	HealthResponseChecksQueueStatusHealthy   HealthResponseChecksQueueStatus = "healthy"
	HealthResponseChecksQueueStatusUnhealthy HealthResponseChecksQueueStatus = "unhealthy"
	HealthResponseChecksQueueStatusUnknown   HealthResponseChecksQueueStatus = "unknown"
)

// Defines values for HealthResponseChecksStorageStatus.
const (
	HealthResponseChecksStorageStatusDegraded  HealthResponseChecksStorageStatus = "degraded"
	HealthResponseChecksStorageStatusHealthy   HealthResponseChecksStorageStatus = "healthy"
	HealthResponseChecksStorageStatusUnhealthy HealthResponseChecksStorageStatus = "unhealthy"
	HealthResponseChecksStorageStatusUnknown   HealthResponseChecksStorageStatus = "unknown"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDEGRADED    HealthResponseStatus = "DEGRADED"
	HealthResponseStatusDOWN        HealthResponseStatus = "DOWN"
	HealthResponseStatusMAINTENANCE HealthResponseStatus = "MAINTENANCE"
	HealthResponseStatusOK          HealthResponseStatus = "OK"
)

// Defines values for LivenessResponseStatus.
const (
	LivenessResponseStatusDEGRADED    LivenessResponseStatus = "DEGRADED"
	LivenessResponseStatusDOWN        LivenessResponseStatus = "DOWN"
	LivenessResponseStatusMAINTENANCE LivenessResponseStatus = "MAINTENANCE"
	LivenessResponseStatusOK          LivenessResponseStatus = "OK"
)

// Defines values for LoginFormMethod.
const (
	LoginFormMethodPOST LoginFormMethod = "POST"
)

// Defines values for ReadinessResponseChecksStatus.
const (
	ReadinessResponseChecksStatusDegraded  ReadinessResponseChecksStatus = "degraded"
	ReadinessResponseChecksStatusHealthy   ReadinessResponseChecksStatus = "healthy"
	ReadinessResponseChecksStatusUnhealthy ReadinessResponseChecksStatus = "unhealthy"
	ReadinessResponseChecksStatusUnknown   ReadinessResponseChecksStatus = "unknown"
)

// Defines values for ReadinessResponseChecksCacheStatus.
const (
	ReadinessResponseChecksCacheStatusDegraded  ReadinessResponseChecksCacheStatus = "degraded"
	ReadinessResponseChecksCacheStatusHealthy   ReadinessResponseChecksCacheStatus = "healthy"
	ReadinessResponseChecksCacheStatusUnhealthy ReadinessResponseChecksCacheStatus = "unhealthy"
	ReadinessResponseChecksCacheStatusUnknown   ReadinessResponseChecksCacheStatus = "unknown"
)

// Defines values for ReadinessResponseChecksQueueStatus.
const (
	ReadinessResponseChecksQueueStatusDegraded  ReadinessResponseChecksQueueStatus = "degraded"
	ReadinessResponseChecksQueueStatusHealthy   ReadinessResponseChecksQueueStatus = "healthy"
	ReadinessResponseChecksQueueStatusUnhealthy ReadinessResponseChecksQueueStatus = "unhealthy"
	ReadinessResponseChecksQueueStatusUnknown   ReadinessResponseChecksQueueStatus = "unknown"
)

// Defines values for ReadinessResponseChecksStorageStatus.
const (
	ReadinessResponseChecksStorageStatusDegraded  ReadinessResponseChecksStorageStatus = "degraded"
	ReadinessResponseChecksStorageStatusHealthy   ReadinessResponseChecksStorageStatus = "healthy"
	ReadinessResponseChecksStorageStatusUnhealthy ReadinessResponseChecksStorageStatus = "unhealthy"
	ReadinessResponseChecksStorageStatusUnknown   ReadinessResponseChecksStorageStatus = "unknown"
)

// Defines values for ReadinessResponseStatus.
const (
	DEGRADED    ReadinessResponseStatus = "DEGRADED"
	DOWN        ReadinessResponseStatus = "DOWN"
	MAINTENANCE ReadinessResponseStatus = "MAINTENANCE"
	OK          ReadinessResponseStatus = "OK"
)

// Defines values for HealthResponseV1DependencyCheckStatus.
const (
	Degraded  HealthResponseV1DependencyCheckStatus = "degraded"
	Healthy   HealthResponseV1DependencyCheckStatus = "healthy"
	Unhealthy HealthResponseV1DependencyCheckStatus = "unhealthy"
	Unknown   HealthResponseV1DependencyCheckStatus = "unknown"
)

// Defines values for ApiVersionHeader.
const (
	ApiVersionHeaderV1 ApiVersionHeader = "v1"
)

// Defines values for GetAnalysisParamsAPIVersion.
const (
	GetAnalysisParamsAPIVersionV1 GetAnalysisParamsAPIVersion = "v1"
)

// Defines values for GetAnalysisEventsParamsAPIVersion.
const (
	GetAnalysisEventsParamsAPIVersionV1 GetAnalysisEventsParamsAPIVersion = "v1"
)

// Defines values for AnalyzeURLParamsAPIVersion.
const (
	AnalyzeURLParamsAPIVersionV1 AnalyzeURLParamsAPIVersion = "v1"
)

// AnalysisData defines model for AnalysisData.
type AnalysisData struct {
	// FetchTimeMs Time spent fetching web page content from the target URL in milliseconds
	FetchTimeMs *int64 `json:"fetch_time_ms,omitempty"`
	Forms       *struct {
		LoginFormDetails *[]struct {
			// Action Form action URL
			Action *string `json:"action,omitempty"`

			// Fields Form field names
			Fields *[]string `json:"fields,omitempty"`

			// Method Form submission method
			Method *AnalysisDataFormsLoginFormDetailsMethod `json:"method,omitempty"`
		} `json:"login_form_details,omitempty"`

		// LoginFormsDetected Number of login forms detected
		LoginFormsDetected *int `json:"login_forms_detected,omitempty"`

		// TotalCount Total number of forms found
		TotalCount *int `json:"total_count,omitempty"`
	} `json:"forms,omitempty"`
	HeadingCounts *struct {
		H1 *int `json:"h1,omitempty"`
		H2 *int `json:"h2,omitempty"`
		H3 *int `json:"h3,omitempty"`
		H4 *int `json:"h4,omitempty"`
		H5 *int `json:"h5,omitempty"`
		H6 *int `json:"h6,omitempty"`
	} `json:"heading_counts,omitempty"`

	// HtmlVersion Detected HTML version
	HtmlVersion *string `json:"html_version,omitempty"`
	Links       *struct {
		// ExternalCount Number of external links
		ExternalCount     *int `json:"external_count,omitempty"`
		InaccessibleLinks *[]struct {
			// Error Error description
			Error *string `json:"error,omitempty"`

			// StatusCode HTTP status code received
			StatusCode *int    `json:"status_code,omitempty"`
			Url        *string `json:"url,omitempty"`
		} `json:"inaccessible_links,omitempty"`

		// InternalCount Number of internal links
		InternalCount *int `json:"internal_count,omitempty"`

		// TotalCount Total number of links
		TotalCount *int `json:"total_count,omitempty"`
	} `json:"links,omitempty"`

	// ProcessingTimeMs Time spent analyzing the HTML content in milliseconds
	ProcessingTimeMs *int64 `json:"processing_time_ms,omitempty"`

	// Title Page title
	Title *string `json:"title,omitempty"`
}

// AnalysisDataFormsLoginFormDetailsMethod Form submission method
type AnalysisDataFormsLoginFormDetailsMethod string

// AnalysisError defines model for AnalysisError.
type AnalysisError struct {
	AnalysisId *openapi_types.UUID `json:"analysis_id,omitempty"`

	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error type
	Error *string `json:"error,omitempty"`

	// ErrorMessage Human-readable error message
	ErrorMessage *string `json:"error_message,omitempty"`

	// HttpStatusCode HTTP status code from the target URL (if applicable)
	HttpStatusCode *int                 `json:"http_status_code,omitempty"`
	Status         *AnalysisErrorStatus `json:"status,omitempty"`
}

// AnalysisErrorStatus defines model for AnalysisError.Status.
type AnalysisErrorStatus string

// AnalysisInProgress defines model for AnalysisInProgress.
type AnalysisInProgress struct {
	AnalysisId *openapi_types.UUID `json:"analysis_id,omitempty"`

	// CurrentStep Current analysis step
	CurrentStep *string `json:"current_step,omitempty"`

	// EstimatedCompletionTime Estimated time to completion
	EstimatedCompletionTime *string `json:"estimated_completion_time,omitempty"`

	// Progress Progress percentage
	Progress *int                      `json:"progress,omitempty"`
	Status   *AnalysisInProgressStatus `json:"status,omitempty"`
}

// AnalysisInProgressStatus defines model for AnalysisInProgress.Status.
type AnalysisInProgressStatus string

// AnalysisResponse defines model for AnalysisResponse.
type AnalysisResponse struct {
	// AnalysisId Unique identifier for the analysis
	AnalysisId *openapi_types.UUID `json:"analysis_id,omitempty"`

	// CreatedAt When the analysis was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EstimatedCompletionTime Estimated time to completion
	EstimatedCompletionTime *string `json:"estimated_completion_time,omitempty"`

	// Status Current status of the analysis
	Status *AnalysisResponseStatus `json:"status,omitempty"`

	// Url The URL being analyzed
	Url *string `json:"url,omitempty"`
}

// AnalysisResponseStatus Current status of the analysis
type AnalysisResponseStatus string

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	AnalysisId  *openapi_types.UUID `json:"analysis_id,omitempty"`
	CompletedAt *time.Time          `json:"completed_at,omitempty"`

	// ContentHash SHA-256 hash of the analyzed content
	ContentHash *string `json:"content_hash,omitempty"`

	// ContentSize Size of the analyzed content in bytes
	ContentSize *int64     `json:"content_size,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// Duration Analysis duration
	Duration *string `json:"duration,omitempty"`
	Results  *struct {
		// FetchTimeMs Time spent fetching web page content from the target URL in milliseconds
		FetchTimeMs *int64 `json:"fetch_time_ms,omitempty"`
		Forms       *struct {
			LoginFormDetails *[]struct {
				// Action Form action URL
				Action *string `json:"action,omitempty"`

				// Fields Form field names
				Fields *[]string `json:"fields,omitempty"`

				// Method Form submission method
				Method *AnalysisResultResultsFormsLoginFormDetailsMethod `json:"method,omitempty"`
			} `json:"login_form_details,omitempty"`

			// LoginFormsDetected Number of login forms detected
			LoginFormsDetected *int `json:"login_forms_detected,omitempty"`

			// TotalCount Total number of forms found
			TotalCount *int `json:"total_count,omitempty"`
		} `json:"forms,omitempty"`
		HeadingCounts *struct {
			H1 *int `json:"h1,omitempty"`
			H2 *int `json:"h2,omitempty"`
			H3 *int `json:"h3,omitempty"`
			H4 *int `json:"h4,omitempty"`
			H5 *int `json:"h5,omitempty"`
			H6 *int `json:"h6,omitempty"`
		} `json:"heading_counts,omitempty"`

		// HtmlVersion Detected HTML version
		HtmlVersion *string `json:"html_version,omitempty"`
		Links       *struct {
			// ExternalCount Number of external links
			ExternalCount     *int `json:"external_count,omitempty"`
			InaccessibleLinks *[]struct {
				// Error Error description
				Error *string `json:"error,omitempty"`

				// StatusCode HTTP status code received
				StatusCode *int    `json:"status_code,omitempty"`
				Url        *string `json:"url,omitempty"`
			} `json:"inaccessible_links,omitempty"`

			// InternalCount Number of internal links
			InternalCount *int `json:"internal_count,omitempty"`

			// TotalCount Total number of links
			TotalCount *int `json:"total_count,omitempty"`
		} `json:"links,omitempty"`

		// ProcessingTimeMs Time spent analyzing the HTML content in milliseconds
		ProcessingTimeMs *int64 `json:"processing_time_ms,omitempty"`

		// Title Page title
		Title *string `json:"title,omitempty"`
	} `json:"results,omitempty"`
	Status *AnalysisResultStatus `json:"status,omitempty"`
	Url    *string               `json:"url,omitempty"`
}

// AnalysisResultResultsFormsLoginFormDetailsMethod Form submission method
type AnalysisResultResultsFormsLoginFormDetailsMethod string

// AnalysisResultStatus defines model for AnalysisResult.Status.
type AnalysisResultStatus string

// AnalyzeRequest defines model for AnalyzeRequest.
type AnalyzeRequest struct {
	Options *struct {
		// CheckLinks Whether to check link accessibility
		CheckLinks *bool `json:"check_links,omitempty"`

		// DetectForms Whether to detect login forms
		DetectForms *bool `json:"detect_forms,omitempty"`

		// IncludeHeadings Whether to include heading analysis
		IncludeHeadings *bool `json:"include_headings,omitempty"`

		// Timeout Request timeout in seconds
		Timeout *int `json:"timeout,omitempty"`
	} `json:"options,omitempty"`

	// Url The URL to analyze (supports absolute URLs, relative paths, and internal links)
	Url string `json:"url"`
}

// CacheDependencyCheck defines model for CacheDependencyCheck.
type CacheDependencyCheck struct {
	Details *CacheDependencyCheck_Details `json:"details,omitempty"`

	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// ResponseTime Response time in milliseconds
	ResponseTime *float32 `json:"response_time,omitempty"`

	// Status Health status of the dependency
	Status CacheDependencyCheckStatus `json:"status"`
}

// CacheDependencyCheck_Details defines model for CacheDependencyCheck.Details.
type CacheDependencyCheck_Details struct {
	PoolStats *struct {
		// Hits Number of times free connection was found in the pool
		Hits int `json:"hits"`

		// IdleConnections Number of idle connections in the pool
		IdleConnections int `json:"idle_connections"`

		// Misses Number of times free connection was NOT found in the pool
		Misses int `json:"misses"`

		// StaleConnections Number of stale connections removed from the pool
		StaleConnections int `json:"stale_connections"`

		// Timeouts Number of times a wait timeout occurred
		Timeouts int `json:"timeouts"`

		// TotalConnections Number of total connections in the pool
		TotalConnections int `json:"total_connections"`

		// WaitCount Number of times a connection was waited
		WaitCount int `json:"wait_count"`

		// WaitDurationNs Total time spent for waiting a connection in nanoseconds
		WaitDurationNs int `json:"wait_duration_ns"`
	} `json:"pool_stats,omitempty"`

	// TotalKeys Total number of keys in cache
	TotalKeys            *int                   `json:"total_keys,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// CacheDependencyCheckStatus Health status of the dependency
type CacheDependencyCheckStatus string

// DependencyCheck defines model for DependencyCheck.
type DependencyCheck struct {
	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// Status Health status of the dependency
	Status DependencyCheckStatus `json:"status"`
}

// DependencyCheckStatus Health status of the dependency
type DependencyCheckStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error *string `json:"error,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RetryAfter Seconds to wait before retrying (for rate limit errors)
	RetryAfter *int `json:"retry_after,omitempty"`

	// StatusCode HTTP status code
	StatusCode *int       `json:"status_code,omitempty"`
	Timestamp  *time.Time `json:"timestamp,omitempty"`
}

// FormAnalysis defines model for FormAnalysis.
type FormAnalysis struct {
	LoginFormDetails *[]struct {
		// Action Form action URL
		Action *string `json:"action,omitempty"`

		// Fields Form field names
		Fields *[]string `json:"fields,omitempty"`

		// Method Form submission method
		Method *FormAnalysisLoginFormDetailsMethod `json:"method,omitempty"`
	} `json:"login_form_details,omitempty"`

	// LoginFormsDetected Number of login forms detected
	LoginFormsDetected *int `json:"login_forms_detected,omitempty"`

	// TotalCount Total number of forms found
	TotalCount *int `json:"total_count,omitempty"`
}

// FormAnalysisLoginFormDetailsMethod Form submission method
type FormAnalysisLoginFormDetailsMethod string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks Status of individual dependencies
	Checks HealthResponse_Checks `json:"checks"`

	// Status Overall health status - OK only if all dependencies are healthy, DEGRADED if some non-critical dependencies are unhealthy
	Status HealthResponseStatus `json:"status"`

	// Timestamp ISO 8601 timestamp when the check was performed
	Timestamp time.Time `json:"timestamp"`

	// Uptime Service uptime in seconds
	Uptime *float32 `json:"uptime,omitempty"`

	// Version Application version
	Version *string `json:"version,omitempty"`
}

// HealthResponseChecksStatus Health status of the dependency
type HealthResponseChecksStatus string

// HealthResponse_Checks_Cache_Details defines model for HealthResponse.Checks.Cache.Details.
type HealthResponse_Checks_Cache_Details struct {
	PoolStats *struct {
		// Hits Number of times free connection was found in the pool
		Hits int `json:"hits"`

		// IdleConnections Number of idle connections in the pool
		IdleConnections int `json:"idle_connections"`

		// Misses Number of times free connection was NOT found in the pool
		Misses int `json:"misses"`

		// StaleConnections Number of stale connections removed from the pool
		StaleConnections int `json:"stale_connections"`

		// Timeouts Number of times a wait timeout occurred
		Timeouts int `json:"timeouts"`

		// TotalConnections Number of total connections in the pool
		TotalConnections int `json:"total_connections"`

		// WaitCount Number of times a connection was waited
		WaitCount int `json:"wait_count"`

		// WaitDurationNs Total time spent for waiting a connection in nanoseconds
		WaitDurationNs int `json:"wait_duration_ns"`
	} `json:"pool_stats,omitempty"`

	// TotalKeys Total number of keys in cache
	TotalKeys            *int                   `json:"total_keys,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HealthResponseChecksCacheStatus Health status of the dependency
type HealthResponseChecksCacheStatus string

// HealthResponseChecksQueueStatus Health status of the dependency
type HealthResponseChecksQueueStatus string

// HealthResponseChecksStorageStatus Health status of the dependency
type HealthResponseChecksStorageStatus string

// HealthResponse_Checks Status of individual dependencies
type HealthResponse_Checks struct {
	Cache *struct {
		Details *HealthResponse_Checks_Cache_Details `json:"details,omitempty"`

		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// ResponseTime Response time in milliseconds
		ResponseTime *float32 `json:"response_time,omitempty"`

		// Status Health status of the dependency
		Status HealthResponseChecksCacheStatus `json:"status"`
	} `json:"cache,omitempty"`
	Queue *struct {
		// Details Additional dependency-specific information
		Details *map[string]interface{} `json:"details,omitempty"`

		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// ResponseTime Response time in milliseconds
		ResponseTime *float32 `json:"response_time,omitempty"`

		// Status Health status of the dependency
		Status HealthResponseChecksQueueStatus `json:"status"`
	} `json:"queue,omitempty"`
	Storage *struct {
		// Details Additional dependency-specific information
		Details *map[string]interface{} `json:"details,omitempty"`

		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// ResponseTime Response time in milliseconds
		ResponseTime *float32 `json:"response_time,omitempty"`

		// Status Health status of the dependency
		Status HealthResponseChecksStorageStatus `json:"status"`
	} `json:"storage,omitempty"`
	AdditionalProperties map[string]struct {
		// Details Additional dependency-specific information
		Details *map[string]interface{} `json:"details,omitempty"`

		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// ResponseTime Response time in milliseconds
		ResponseTime *float32 `json:"response_time,omitempty"`

		// Status Health status of the dependency
		Status HealthResponseChecksStatus `json:"status"`
	} `json:"-"`
}

// HealthResponseStatus Overall health status - OK only if all dependencies are healthy, DEGRADED if some non-critical dependencies are unhealthy
type HealthResponseStatus string

// InaccessibleLink defines model for InaccessibleLink.
type InaccessibleLink struct {
	// Error Error description
	Error *string `json:"error,omitempty"`

	// StatusCode HTTP status code received
	StatusCode *int    `json:"status_code,omitempty"`
	Url        *string `json:"url,omitempty"`
}

// LinkAnalysis defines model for LinkAnalysis.
type LinkAnalysis struct {
	// ExternalCount Number of external links
	ExternalCount     *int `json:"external_count,omitempty"`
	InaccessibleLinks *[]struct {
		// Error Error description
		Error *string `json:"error,omitempty"`

		// StatusCode HTTP status code received
		StatusCode *int    `json:"status_code,omitempty"`
		Url        *string `json:"url,omitempty"`
	} `json:"inaccessible_links,omitempty"`

	// InternalCount Number of internal links
	InternalCount *int `json:"internal_count,omitempty"`

	// TotalCount Total number of links
	TotalCount *int `json:"total_count,omitempty"`
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	// Status Service liveness status - OK if service is running, DEGRADED if running with reduced capacity
	Status LivenessResponseStatus `json:"status"`

	// Timestamp ISO 8601 timestamp when the check was performed
	Timestamp time.Time `json:"timestamp"`

	// Version API version
	Version string `json:"version"`
}

// LivenessResponseStatus Service liveness status - OK if service is running, DEGRADED if running with reduced capacity
type LivenessResponseStatus string

// LoginForm defines model for LoginForm.
type LoginForm struct {
	// Action Form action URL
	Action *string `json:"action,omitempty"`

	// Fields Form field names
	Fields *[]string `json:"fields,omitempty"`

	// Method Form submission method
	Method *LoginFormMethod `json:"method,omitempty"`
}

// LoginFormMethod Form submission method
type LoginFormMethod string

// Pagination defines model for Pagination.
type Pagination struct {
	HasNext     *bool `json:"has_next,omitempty"`
	HasPrevious *bool `json:"has_previous,omitempty"`
	Limit       *int  `json:"limit,omitempty"`
	Page        *int  `json:"page,omitempty"`
	TotalCount  *int  `json:"total_count,omitempty"`
	TotalPages  *int  `json:"total_pages,omitempty"`
}

// PoolStats defines model for PoolStats.
type PoolStats struct {
	// Hits Number of times free connection was found in the pool
	Hits int `json:"hits"`

	// IdleConnections Number of idle connections in the pool
	IdleConnections int `json:"idle_connections"`

	// Misses Number of times free connection was NOT found in the pool
	Misses int `json:"misses"`

	// StaleConnections Number of stale connections removed from the pool
	StaleConnections int `json:"stale_connections"`

	// Timeouts Number of times a wait timeout occurred
	Timeouts int `json:"timeouts"`

	// TotalConnections Number of total connections in the pool
	TotalConnections int `json:"total_connections"`

	// WaitCount Number of times a connection was waited
	WaitCount int `json:"wait_count"`

	// WaitDurationNs Total time spent for waiting a connection in nanoseconds
	WaitDurationNs int `json:"wait_duration_ns"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	// Checks Status of individual dependencies
	Checks ReadinessResponse_Checks `json:"checks"`

	// Status Overall readiness status - ready only if all dependencies are healthy, DEGRADED if some non-critical dependencies are unhealthy
	Status ReadinessResponseStatus `json:"status"`

	// Timestamp ISO 8601 timestamp when the check was performed
	Timestamp time.Time `json:"timestamp"`

	// Version Application version
	Version *string `json:"version,omitempty"`
}

// ReadinessResponseChecksStatus Health status of the dependency
type ReadinessResponseChecksStatus string

// ReadinessResponseChecksCacheStatus Health status of the dependency
type ReadinessResponseChecksCacheStatus string

// ReadinessResponseChecksQueueStatus Health status of the dependency
type ReadinessResponseChecksQueueStatus string

// ReadinessResponseChecksStorageStatus Health status of the dependency
type ReadinessResponseChecksStorageStatus string

// ReadinessResponse_Checks Status of individual dependencies
type ReadinessResponse_Checks struct {
	Cache *struct {
		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// Status Health status of the dependency
		Status ReadinessResponseChecksCacheStatus `json:"status"`
	} `json:"cache,omitempty"`
	Queue *struct {
		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// Status Health status of the dependency
		Status ReadinessResponseChecksQueueStatus `json:"status"`
	} `json:"queue,omitempty"`
	Storage *struct {
		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// Status Health status of the dependency
		Status ReadinessResponseChecksStorageStatus `json:"status"`
	} `json:"storage,omitempty"`
	AdditionalProperties map[string]struct {
		// Error Error message if the dependency is unhealthy
		Error *string `json:"error,omitempty"`

		// LastChecked When this dependency was last checked
		LastChecked *time.Time `json:"last_checked,omitempty"`

		// Status Health status of the dependency
		Status ReadinessResponseChecksStatus `json:"status"`
	} `json:"-"`
}

// ReadinessResponseStatus Overall readiness status - ready only if all dependencies are healthy, DEGRADED if some non-critical dependencies are unhealthy
type ReadinessResponseStatus string

// HealthResponseV1DependencyCheck defines model for health-response.v1_DependencyCheck.
type HealthResponseV1DependencyCheck struct {
	// Details Additional dependency-specific information
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// ResponseTime Response time in milliseconds
	ResponseTime *float32 `json:"response_time,omitempty"`

	// Status Health status of the dependency
	Status HealthResponseV1DependencyCheckStatus `json:"status"`
}

// HealthResponseV1DependencyCheckStatus Health status of the dependency
type HealthResponseV1DependencyCheckStatus string

// ApiVersionHeader defines model for ApiVersionHeader.
type ApiVersionHeader string

// BadRequest defines model for bad_request.
type BadRequest struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error *string `json:"error,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RetryAfter Seconds to wait before retrying (for rate limit errors)
	RetryAfter *int `json:"retry_after,omitempty"`

	// StatusCode HTTP status code
	StatusCode *int       `json:"status_code,omitempty"`
	Timestamp  *time.Time `json:"timestamp,omitempty"`
}

// NotFound defines model for not_found.
type NotFound struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error *string `json:"error,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RetryAfter Seconds to wait before retrying (for rate limit errors)
	RetryAfter *int `json:"retry_after,omitempty"`

	// StatusCode HTTP status code
	StatusCode *int       `json:"status_code,omitempty"`
	Timestamp  *time.Time `json:"timestamp,omitempty"`
}

// RateLimit defines model for rate_limit.
type RateLimit struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error *string `json:"error,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RetryAfter Seconds to wait before retrying (for rate limit errors)
	RetryAfter *int `json:"retry_after,omitempty"`

	// StatusCode HTTP status code
	StatusCode *int       `json:"status_code,omitempty"`
	Timestamp  *time.Time `json:"timestamp,omitempty"`
}

// ServerError defines model for server_error.
type ServerError struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error *string `json:"error,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RetryAfter Seconds to wait before retrying (for rate limit errors)
	RetryAfter *int `json:"retry_after,omitempty"`

	// StatusCode HTTP status code
	StatusCode *int       `json:"status_code,omitempty"`
	Timestamp  *time.Time `json:"timestamp,omitempty"`
}

// Unauthorized defines model for unauthorized.
type Unauthorized struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error *string `json:"error,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// RetryAfter Seconds to wait before retrying (for rate limit errors)
	RetryAfter *int `json:"retry_after,omitempty"`

	// StatusCode HTTP status code
	StatusCode *int       `json:"status_code,omitempty"`
	Timestamp  *time.Time `json:"timestamp,omitempty"`
}

// GetAnalysisParams defines parameters for GetAnalysis.
type GetAnalysisParams struct {
	// APIVersion API version to use for this request. If not specified, defaults to v1.
	// Supported versions: v1
	APIVersion *GetAnalysisParamsAPIVersion `json:"API-Version,omitempty"`
}

// GetAnalysisParamsAPIVersion defines parameters for GetAnalysis.
type GetAnalysisParamsAPIVersion string

// GetAnalysisEventsParams defines parameters for GetAnalysisEvents.
type GetAnalysisEventsParams struct {
	// Token PASETO authentication token for SSE connection
	Token string `form:"token" json:"token"`

	// APIVersion API version to use for this request. If not specified, defaults to v1.
	// Supported versions: v1
	APIVersion *GetAnalysisEventsParamsAPIVersion `json:"API-Version,omitempty"`
}

// GetAnalysisEventsParamsAPIVersion defines parameters for GetAnalysisEvents.
type GetAnalysisEventsParamsAPIVersion string

// AnalyzeURLJSONBody defines parameters for AnalyzeURL.
type AnalyzeURLJSONBody struct {
	Options *struct {
		// CheckLinks Whether to check link accessibility
		CheckLinks *bool `json:"check_links,omitempty"`

		// DetectForms Whether to detect login forms
		DetectForms *bool `json:"detect_forms,omitempty"`

		// IncludeHeadings Whether to include heading analysis
		IncludeHeadings *bool `json:"include_headings,omitempty"`

		// Timeout Request timeout in seconds
		Timeout *int `json:"timeout,omitempty"`
	} `json:"options,omitempty"`

	// Url The URL to analyze (supports absolute URLs, relative paths, and internal links)
	Url string `json:"url"`
}

// AnalyzeURLParams defines parameters for AnalyzeURL.
type AnalyzeURLParams struct {
	// APIVersion API version to use for this request. If not specified, defaults to v1.
	// Supported versions: v1
	APIVersion *AnalyzeURLParamsAPIVersion `json:"API-Version,omitempty"`
}

// AnalyzeURLParamsAPIVersion defines parameters for AnalyzeURL.
type AnalyzeURLParamsAPIVersion string

// AnalyzeURLJSONRequestBody defines body for AnalyzeURL for application/json ContentType.
type AnalyzeURLJSONRequestBody AnalyzeURLJSONBody

// Getter for additional properties for CacheDependencyCheck_Details. Returns the specified
// element and whether it was found
func (a CacheDependencyCheck_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CacheDependencyCheck_Details
func (a *CacheDependencyCheck_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CacheDependencyCheck_Details to handle AdditionalProperties
func (a *CacheDependencyCheck_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["pool_stats"]; found {
		err = json.Unmarshal(raw, &a.PoolStats)
		if err != nil {
			return fmt.Errorf("error reading 'pool_stats': %w", err)
		}
		delete(object, "pool_stats")
	}

	if raw, found := object["total_keys"]; found {
		err = json.Unmarshal(raw, &a.TotalKeys)
		if err != nil {
			return fmt.Errorf("error reading 'total_keys': %w", err)
		}
		delete(object, "total_keys")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CacheDependencyCheck_Details to handle AdditionalProperties
func (a CacheDependencyCheck_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PoolStats != nil {
		object["pool_stats"], err = json.Marshal(a.PoolStats)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pool_stats': %w", err)
		}
	}

	if a.TotalKeys != nil {
		object["total_keys"], err = json.Marshal(a.TotalKeys)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'total_keys': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HealthResponse_Checks_Cache_Details. Returns the specified
// element and whether it was found
func (a HealthResponse_Checks_Cache_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HealthResponse_Checks_Cache_Details
func (a *HealthResponse_Checks_Cache_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HealthResponse_Checks_Cache_Details to handle AdditionalProperties
func (a *HealthResponse_Checks_Cache_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["pool_stats"]; found {
		err = json.Unmarshal(raw, &a.PoolStats)
		if err != nil {
			return fmt.Errorf("error reading 'pool_stats': %w", err)
		}
		delete(object, "pool_stats")
	}

	if raw, found := object["total_keys"]; found {
		err = json.Unmarshal(raw, &a.TotalKeys)
		if err != nil {
			return fmt.Errorf("error reading 'total_keys': %w", err)
		}
		delete(object, "total_keys")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HealthResponse_Checks_Cache_Details to handle AdditionalProperties
func (a HealthResponse_Checks_Cache_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PoolStats != nil {
		object["pool_stats"], err = json.Marshal(a.PoolStats)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pool_stats': %w", err)
		}
	}

	if a.TotalKeys != nil {
		object["total_keys"], err = json.Marshal(a.TotalKeys)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'total_keys': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HealthResponse_Checks. Returns the specified
// element and whether it was found
func (a HealthResponse_Checks) Get(fieldName string) (value struct {
	// Details Additional dependency-specific information
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// ResponseTime Response time in milliseconds
	ResponseTime *float32 `json:"response_time,omitempty"`

	// Status Health status of the dependency
	Status HealthResponseChecksStatus `json:"status"`
}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HealthResponse_Checks
func (a *HealthResponse_Checks) Set(fieldName string, value struct {
	// Details Additional dependency-specific information
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// ResponseTime Response time in milliseconds
	ResponseTime *float32 `json:"response_time,omitempty"`

	// Status Health status of the dependency
	Status HealthResponseChecksStatus `json:"status"`
}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]struct {
			// Details Additional dependency-specific information
			Details *map[string]interface{} `json:"details,omitempty"`

			// Error Error message if the dependency is unhealthy
			Error *string `json:"error,omitempty"`

			// LastChecked When this dependency was last checked
			LastChecked *time.Time `json:"last_checked,omitempty"`

			// ResponseTime Response time in milliseconds
			ResponseTime *float32 `json:"response_time,omitempty"`

			// Status Health status of the dependency
			Status HealthResponseChecksStatus `json:"status"`
		})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HealthResponse_Checks to handle AdditionalProperties
func (a *HealthResponse_Checks) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cache"]; found {
		err = json.Unmarshal(raw, &a.Cache)
		if err != nil {
			return fmt.Errorf("error reading 'cache': %w", err)
		}
		delete(object, "cache")
	}

	if raw, found := object["queue"]; found {
		err = json.Unmarshal(raw, &a.Queue)
		if err != nil {
			return fmt.Errorf("error reading 'queue': %w", err)
		}
		delete(object, "queue")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]struct {
			// Details Additional dependency-specific information
			Details *map[string]interface{} `json:"details,omitempty"`

			// Error Error message if the dependency is unhealthy
			Error *string `json:"error,omitempty"`

			// LastChecked When this dependency was last checked
			LastChecked *time.Time `json:"last_checked,omitempty"`

			// ResponseTime Response time in milliseconds
			ResponseTime *float32 `json:"response_time,omitempty"`

			// Status Health status of the dependency
			Status HealthResponseChecksStatus `json:"status"`
		})
		for fieldName, fieldBuf := range object {
			var fieldVal struct {
				// Details Additional dependency-specific information
				Details *map[string]interface{} `json:"details,omitempty"`

				// Error Error message if the dependency is unhealthy
				Error *string `json:"error,omitempty"`

				// LastChecked When this dependency was last checked
				LastChecked *time.Time `json:"last_checked,omitempty"`

				// ResponseTime Response time in milliseconds
				ResponseTime *float32 `json:"response_time,omitempty"`

				// Status Health status of the dependency
				Status HealthResponseChecksStatus `json:"status"`
			}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HealthResponse_Checks to handle AdditionalProperties
func (a HealthResponse_Checks) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Cache != nil {
		object["cache"], err = json.Marshal(a.Cache)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cache': %w", err)
		}
	}

	if a.Queue != nil {
		object["queue"], err = json.Marshal(a.Queue)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'queue': %w", err)
		}
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ReadinessResponse_Checks. Returns the specified
// element and whether it was found
func (a ReadinessResponse_Checks) Get(fieldName string) (value struct {
	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// Status Health status of the dependency
	Status ReadinessResponseChecksStatus `json:"status"`
}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReadinessResponse_Checks
func (a *ReadinessResponse_Checks) Set(fieldName string, value struct {
	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked When this dependency was last checked
	LastChecked *time.Time `json:"last_checked,omitempty"`

	// Status Health status of the dependency
	Status ReadinessResponseChecksStatus `json:"status"`
}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]struct {
			// Error Error message if the dependency is unhealthy
			Error *string `json:"error,omitempty"`

			// LastChecked When this dependency was last checked
			LastChecked *time.Time `json:"last_checked,omitempty"`

			// Status Health status of the dependency
			Status ReadinessResponseChecksStatus `json:"status"`
		})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReadinessResponse_Checks to handle AdditionalProperties
func (a *ReadinessResponse_Checks) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cache"]; found {
		err = json.Unmarshal(raw, &a.Cache)
		if err != nil {
			return fmt.Errorf("error reading 'cache': %w", err)
		}
		delete(object, "cache")
	}

	if raw, found := object["queue"]; found {
		err = json.Unmarshal(raw, &a.Queue)
		if err != nil {
			return fmt.Errorf("error reading 'queue': %w", err)
		}
		delete(object, "queue")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]struct {
			// Error Error message if the dependency is unhealthy
			Error *string `json:"error,omitempty"`

			// LastChecked When this dependency was last checked
			LastChecked *time.Time `json:"last_checked,omitempty"`

			// Status Health status of the dependency
			Status ReadinessResponseChecksStatus `json:"status"`
		})
		for fieldName, fieldBuf := range object {
			var fieldVal struct {
				// Error Error message if the dependency is unhealthy
				Error *string `json:"error,omitempty"`

				// LastChecked When this dependency was last checked
				LastChecked *time.Time `json:"last_checked,omitempty"`

				// Status Health status of the dependency
				Status ReadinessResponseChecksStatus `json:"status"`
			}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReadinessResponse_Checks to handle AdditionalProperties
func (a ReadinessResponse_Checks) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Cache != nil {
		object["cache"], err = json.Marshal(a.Cache)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cache': %w", err)
		}
	}

	if a.Queue != nil {
		object["queue"], err = json.Marshal(a.Queue)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'queue': %w", err)
		}
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get analysis result
	// (GET /v1/analysis/{analysisId})
	GetAnalysis(w http.ResponseWriter, r *http.Request, analysisId openapi_types.UUID, params GetAnalysisParams)
	// Get real-time analysis progress
	// (GET /v1/analysis/{analysisId}/events)
	GetAnalysisEvents(w http.ResponseWriter, r *http.Request, analysisId openapi_types.UUID, params GetAnalysisEventsParams)
	// Analyze a web page
	// (POST /v1/analyze)
	AnalyzeURL(w http.ResponseWriter, r *http.Request, params AnalyzeURLParams)
	// Health check
	// (GET /v1/health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /v1/liveness)
	LivenessCheck(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /v1/readiness)
	ReadinessCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get analysis result
// (GET /v1/analysis/{analysisId})
func (_ Unimplemented) GetAnalysis(w http.ResponseWriter, r *http.Request, analysisId openapi_types.UUID, params GetAnalysisParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get real-time analysis progress
// (GET /v1/analysis/{analysisId}/events)
func (_ Unimplemented) GetAnalysisEvents(w http.ResponseWriter, r *http.Request, analysisId openapi_types.UUID, params GetAnalysisEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Analyze a web page
// (POST /v1/analyze)
func (_ Unimplemented) AnalyzeURL(w http.ResponseWriter, r *http.Request, params AnalyzeURLParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /v1/health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /v1/liveness)
func (_ Unimplemented) LivenessCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /v1/readiness)
func (_ Unimplemented) ReadinessCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAnalysis operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysis(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "analysisId" -------------
	var analysisId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", chi.URLParam(r, "analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, PasetoAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnalysisParams

	headers := r.Header

	// ------------- Optional header parameter "API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("API-Version")]; found {
		var APIVersion GetAnalysisParamsAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "API-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "API-Version", valueList[0], &APIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "API-Version", Err: err})
			return
		}

		params.APIVersion = &APIVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysis(w, r, analysisId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalysisEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysisEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "analysisId" -------------
	var analysisId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", chi.URLParam(r, "analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, PasetoQueryAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnalysisEventsParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("API-Version")]; found {
		var APIVersion GetAnalysisEventsParamsAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "API-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "API-Version", valueList[0], &APIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "API-Version", Err: err})
			return
		}

		params.APIVersion = &APIVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysisEvents(w, r, analysisId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnalyzeURL operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeURL(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, PasetoAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AnalyzeURLParams

	headers := r.Header

	// ------------- Optional header parameter "API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("API-Version")]; found {
		var APIVersion AnalyzeURLParamsAPIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "API-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "API-Version", valueList[0], &APIVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "API-Version", Err: err})
			return
		}

		params.APIVersion = &APIVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeURL(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LivenessCheck operation middleware
func (siw *ServerInterfaceWrapper) LivenessCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LivenessCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadinessCheck operation middleware
func (siw *ServerInterfaceWrapper) ReadinessCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadinessCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/analysis/{analysisId}", wrapper.GetAnalysis)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/analysis/{analysisId}/events", wrapper.GetAnalysisEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/analyze", wrapper.AnalyzeURL)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/liveness", wrapper.LivenessCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/readiness", wrapper.ReadinessCheck)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PbOLLoX0FxP0yyV5Kplx86tR88k2ST2kziazt3zz3jlAYiWxYmJKgFQNmalP/7",
	"KbxIkIRkSfE8kuGXGUfEo7vR3Wg0Gt2fgyhLlxkFKngw+RzAPU6XCai/aSamDHC8nnJgKxKB/JHnaYrZ",
	"OpgEV/pHRDiimUCqZdAJVjjJVctoAdEnNVCEo4X6CRjLWDAJLiEmHMlRgaGcMsDRAs8SCDpBgrmYqq4Q",
	"B5NgEA7G3bDf7Y+v++FkGE7C8H+CTsAFFjkPJkFOF4ATsVgHD53gPznklXl+BM7xLSD1AUUZpRAJklEk",
	"SApZLr5wPi4yhm8rM77AAs8wr0w2xySB+IvmenB+fvH+3++CTiBR4AKny80jrYBxktFgEvR7YS/Uw+hV",
	"m8bZHd24nuqjs5TF3D+ev3l3/fLd+bsfXu4LwqqEoUDsUcYqSbAPYzm0X2ZZguB+gXMuvnANtvDXjGWf",
	"npSTPZz1w9Ny72EclS9lo2DSPw3D3sDHYQ+dYAE4BqYW6HxJ/p9u8lr9KH+LgUeMLIXud37xBplRUM4h",
	"RvOMIbEgHDHgy4xySUoeLSDFiho0T4PJT8GqH3zsWG2luEsisF7Kv7lghN5qWJaY4RTEQeCITELkAvSf",
	"HLjooTdzpfH4EiIyJxB3UAxznCeCyz6rfu+GXuXLZcYExHY0PkGr/o2UqhrQRE6rSRZ0AooleSUYXQNp",
	"BX0zj+1bpYYHfUtDhf0Mx1ODgxKejAqg6k+8XCYkwpIGR7/wjNZ3AkJXOCHxNFNk4lVxfaM/IkxxsuaE",
	"I9vKEdkYBCaJ5LVrzbsozblAM0AzEHcAFI0RpjEahiHiEGU0lt0t69en7wSpFrwts6Mly1YkVjKvGX0a",
	"ZTEEk1EY7sDqknh22pwlfow/XL6V3JFi4cdVfrd4YqT7vL6+vkAZU/+/kiN48JQTujheL6BAR01qtlzV",
	"+nD8UsI5obeKJwiDeDonkMRVVH/UbZBtg3Qb/9IuAH2Xs+Q73QgZkZHdHCQ3zOrie1mZTI5jOh2K64Mr",
	"Q0uWLYEJolm7AL+hCeKYyD9xghToyLZsCFqBW32Il6qfAtXTqcC33u11nmLalfaU3EnM7La1ZyAGgq2n",
	"eC58Cu1KS5NUTHeYSFacZwyQ6iMX9plUbwwLQAlJidCz8eflPIQKuAUWPNRo34BaMrZuUUPZGcFZq8+B",
	"EZ1JEGMBXbWxNJVY8Us2+wUioRezOvP3OLa6GXWRK5wZQ84G8NBRJu08y2m8pwK02mVaGaAUk3OrfaRY",
	"6u9eEXmXlYpKNUN3RCyQcAX8zQtHWjwTu5LinbcmIqMd1UHOgW3C7wMHtgNucoiNeEUMYqCC4MTV7bVZ",
	"XeQakx6EWCv737LsXwLPchaBwyeSKljAVOG0p5zHmCRr3XMK9xGANCAqkvBCtrD0si288vCKASiJ4Agz",
	"Q2KI5WL0w9CoAeBoCQzFeO2IhBcIVzA0DIUiaQBTYYrTY7VLVmVncLajUigpuYEelw77bCVH2XCC+qFV",
	"2Br/lNBcgEMC37QViyjLUIrpuhimhy4SkOduwdYI32JCUYKFMqkr1Dg+lBStGvmW1UiDn1AX+TjbOFCA",
	"TYv12usYJYBRnEzrY7hHC93EOsd0E69A+RlenU7NvjtLIJXyxQkXvIMkpDgSiOuzaeXg4QOsamignML9",
	"EiKpwzQ/ZVGUM9Y8YY13PoFYZ1RO8QqTRDlOvK4gAekyY5hJvec23ngO4a4PKQZ2m0lOTbHElGIagUdh",
	"EIowmsOdUUeuleID1CWP47LaDGqNSMNW7/zl9Y5f3JWLFOdikTHyK+x7VoH7pTpXi+wT1Fy8L/UnJMeW",
	"prgeBemW25QMgzkDvkDrLGe6uTxbJdmtlBkpPI6sVOevKBHPtGiBOTJdmiZ+f09XjXvG8LpsNMjVo8hm",
	"tJVnVSPtdFGeqkJtePw31eGbvipIMUn04ZTzu4w9AeKexS48YzsvdsXPpFeHcJTiRLI7xBLicqXqSO+4",
	"3IQj0+NwpK0LyYO09VftzeEG78JP9z1gBpbXCVVb6rkRST1m4bOte7Z2p4TjHjuIFO3m8C1vDh+cPcBx",
	"bEmiebk8KPlB33aYA+ILLDwMMgcRLaYSumnqYZNrkgLiS6ACqZZyujuYoSW+VZebQn1hWaokQ2B2C0L7",
	"pilKSZIQx41vLzyGo0GnpA6h4ngkxYRQkuZpMAl9lJXNeRN6pcen8uPU4XQiwNcYRxqpOo6vMpYi/dF4",
	"4hs8qDzQfENX7Z6mOFW2YjF5YxDzA2YMr7WEiEUWbxiU5zO1vBlFpl15z3Px/urad9PTYKbmnCXBuKSY",
	"suObELzL0xkwlM3NRqnao6L9Y4slMoGTaZTl2lKpn7EEThAtZtBjF26/LQP78JPaVypbNZlnzRd9+d/t",
	"4C4GO7QZ7tBmtEOb8Q5tjh9r46WESJNpcRFbp/oLs3bo9fWPb+1lZOUWUn4Y+3g/IfSTh7Jwbw6LG9a5",
	"5CHbEumRHuMeQnEUAedklsC0mHyDTG/dmtzfPIjtpe8RgwjISnF/E2ZzN1gotZyR4CD5LI7gj1LVttyR",
	"qnvJ5C5D+rBZskytnLR+dthRlOvyV7mlyM1DcabdUrZsH/3BeO/tQxCReBb5Qu5i+psrCi/1X+hFlmrL",
	"foeFtLvsS8uQtb3HXuCQuMooOYl9vPnb222q9aZO0yez3hZCLKf7SZrPnHhG5siceGcJbLPf3PAQE3L1",
	"ca8VfEMvWHbLgPMvX0blGaNiygUsm5j/oL+WLnzVzOXEQkKmViSb68UFSbGAeBplspcce6rDcxoLb5uq",
	"0CFpM5ddfEMvHTrUBMd8QUtgEVChFz/F91oG+2H4mEQ2F4vQaTHhfit2aUOEHluvumFN/pMDIuqQPifq",
	"zpIpxrPdgs4OS8xAUR979Oq/F0ArA6I7zJHp4Q6+5YjwlCtcMtYw5Ju3xM2casQ0m9fJZBfROM4Vdu6C",
	"dgIDiMZ7k1wWO2ltz1iA0gIzUMcdJRRVAu684To8oyKovljCLVqGAXZbUrPNTReYLzyH2tfn3cH4GMmv",
	"FVrLE6B1AbqrCcNZGI1Gg7PTedSP+qMzPJ/NR9Hp2dnxfHY2GA1OMIz6MDoenc3OhqMIj87GZ2f92cnp",
	"eDA7HY+3gcjJrx5GuyK/wibQ5OY9WxvPeblrD0eebbupGKrytBs545xh/9muiIwomrh064+53+MgeYO3",
	"h+X2sNweltvDcntYbg/L7WH5KQ/LTeO/tA63GIUHWnu/wmUZ7l6VCCeSvfpBXfmVAlUE3AuWQ6dp5YuF",
	"uiQyN4WyG7JySRIi1iW0syxLAFNzxodITIvdetdJdD93t/EOT2iU5DFMjdbfawrTF5m+rqXfnMi+Q3HH",
	"H4bNED0dmmtaS6Yt+bU4OQ4rJ8fxbpK09cwgMmugomcm5IUjPONZkgvVgncQgwQLsgK0xGLBO+pmt6oy",
	"nld4fiHEkk+OjswvvShLm4eRFN+/BXorFuo8bPCyvwx97FvcA05+Ujh99OD6A44W8AKWQGOg0foHyXDK",
	"XkuS9/Ng8tOWC0BcuI4unCY+TnCcTHExVdc8dIkQoRrVylZRgrh1mzGuIkT02aEcvv7Oq6R288kTUreB",
	"aByGYeq14KsPojYcy+WpoJxensxlN2S77Xo8t49rNhzJrXNCn8i3qOrRoFfyu95eth3JXytK1U7kJT6O",
	"BVzSNIZbhnUQpUvqnH6i2R31W8kuUxpYPHx5INtVOy2zLFG+Qp9tSgTftsOrq1c0Z1B5cykXVQeim7t7",
	"OUVtf3zUVUXiBKbloFvBkG0dAPimeU8em1SeZ+BAjN+9v96OtTxTPuqe2x1p1biCNYM0W0FcHnbrEAwe",
	"N0KUpO9AAaxv/q1qcMIRy0P0rgbfTuiqxrsscv9R1pKQP269Wjxryyw7V/EcjXea0PpCpj48tXkrHFdG",
	"xtRUyg5wYSAUUUwzn9UpNXP4mBO4plyUhBeM73BAhUweFHzL55FaH1P7dlg92CdY88dtf9lK0kG/QK7o",
	"ldHJvkeC5i8fHzqBZ6/f41R3wHa79e36H7rTfh1boab85juJNiTrKwvJ6igno/Ukt37V1q9aw0/rn80S",
	"X2aq8NvC7ZmtPbP9ERtVTW8XUBEakxWJc5eViNIrNb62eVda50PLyK3zoXU+tM6H1vnQOh++IedDkeqs",
	"3dfbff33N1Cd/HctA7YM+Hsz4PbQhSrg71fAcJKgRQWBLnr/L5TRZC05Q352z1MqH4yBt4NevPzn5fmL",
	"ly9kS56lgGhGuxEjgkTY06/CVIYk7/8VdAI7jvxTJ3R0s3X6oisqLrLaw/Sr9+j0OOyjog26szHNOtZB",
	"MtgSmH4avDN32QSSTd+hTqCgv1djBEqD6jgMvUy1MaDrvHwr7w3n0lkrd+QTl2Ad69vxaa83TmzWW0I/",
	"fXsBWRKrzX7RNuitDXprcswKKPAtTzY2KVirGhIzQkXFSp1Z5l5hOaWE3lZ1qvlRZ6RjEOcRxCjCSxzp",
	"+KyvT4luVndl9tpaotnD9Zwdz6fo3ma3hL7KWNped8g5LvAtocV7hJonCfMphXvhAOtE0smvSwYrkuXc",
	"36LIZlcIXt8ny0tjNW9vVZP4XdSDHJgfEnF9kWXJVetda71rrXet9a79Ud61SxXOvNX82Peuto2++VYv",
	"Ndt1/lOv8wbXdLtOX4sPt12pr97Zyex+Wh7GVf2n1uW5z2n9D3FOalJ2rZu/t+pPH400bm9d2luX30UR",
	"cYhyRsT6KlpAqnnve8xJdJ4LT7oM9UlX1Knl+5TnGxzLgwoXTL/wAxovM0LV2UMlSVQOFjlCuR4LIZba",
	"kcNBZHbSmUoF+squ48X51cvr90Gd3fXP6NlFgoVcc1RL+nllUEPXKvvny/togektqCeH75egjz78OVqN",
	"dH7Q3g09R4oeYBKGak7SfkzCeQ5M5yrV48txgC4wjSBGlo5oDljkDHjvhmoEJjaz6WrUS7IIJ73PS7xO",
	"Mhw/oIw5H5f5LCFR+bX3mZNbqkZ7uKEVIqo+m6j4f3Nga//6GZJp7JaYc4gR5ug/skdZuEUt5ssVUHGl",
	"Sz04h73eDf1gi4ZdXb0sF1mqbgYoyrnIUpOqVW8mqnJXUZ1rtkYzlt1xYC6J/LTZhSiqmpdCoCzmZfPB",
	"WpfkkvwL1jrhp1SCNr0zjpTDwHT6N8yQenhtXjIzdFWkbVdXCsVb1FsiFvmsF2XpEWbRggiQBxl2xFdR",
	"9w5mXfMIljXPSOcqSYmTTxqJBbYPzoEXKUx0xmOTIZeb1wkQuyoc4VmWi8kN7VZyJ8h/l8/H1VfzsFin",
	"opD0T2AFifxUJMNWrFy5GdKfy8uf8te3RYi4iRBXs97Qv/0NnV+8QaaIGqG38sdrqa7lzzkHjjikWMqn",
	"BVa/d45R8Vg4zRNBlgm4DZQ+gVsCfKKn+ZudA13pT2sJ1t///uHyLbrAYuGA8Pe/T9DPR6v+0c/o2ZKR",
	"FLO18Tc/1310Vbp6D6cY3ASt+j8bdkbPcKJoJNWbGeAHkxjger2E+jBu3vAVjXsub/RW/f/zC8/oz/qR",
	"RrFJZ6ViqmP7plx8Ofe5sgpNtbniGbkLewG3PJBLOExGA7f6nxzJNC8tBa0otfTGWZSnQAUUflD9Nclu",
	"Zd/vGeBPir1MH7PxoBT/IiXYTEVoxEAOYzjF6uYmj1RUVHWTmWiSuy24JPSXbQCo69HievANmr+GA9JM",
	"xOXP/kXhAtMYM2d8ox8VRj//d9dwUVdyUfe9zpQwQTTjlMznP5tGr6R6Lr++ePnu/9tP/3111b1gmZHG",
	"Cer/F0qzGP4xS7Lok250JRiJRPeaYcqlsHUt+BOU4vsuvoV/DPvj4XEYhv9lAb/KZzrXBNdjWDBt1+5F",
	"lpBoPbHVGLucReg7Dsn8O93hEubAGLCiIddQZIzcEtqV1n43Yhnn5hfd6wKYuRziRccIp8DwP54976CU",
	"RCxbLjIK6p+3kMmtQyL+j2fPf1abQkIiMD5Ho91/fHPd0OPZEqguZtTL2O2R6cSPZNsyOYdnYzi/eOMr",
	"9toJ5Ih4SYJJMOyFvWHQCVSaAwmH1EI2t8PRZ/vXm/hBfrwF4TNBBSOwAq6kTmfKkhYjRvbiKlnrizQh",
	"pdNJHFEokTdxMAn+CeK8/ObW5/zpWy7G2fGlqcgbiQg9CfYKCMfjEE5HYdiFwdmsO+rHoy4+6R93R6Pj",
	"4/F4NArDMLQ4yIUuMSjXN3BtcX1qKxF6JOfdw8daQdFBGO5Zm8JJmudEj5Tp+3+w38vEiZrT3Nz9lUx9",
	"u1Klmq6vmVC/P/6foJ6eL8Djsz4+jkfhbD4ahKNwhMN+/2Q4jOazk1n/LIyPB9HxeDYPZ1GMh4PZ+GQ2",
	"ODmJz3B8Nu+PjiGoZ9PrD8bH1Ux3myrtlpntTLI6JzddLRtdkSlu46PEn8r7+OBINQjKa/afVA0+xSlS",
	"Hk1Fio/llbm+Aper73+/169dKA+8GccWfdVyMVBXd4uhSvKyGKlrw8VYXSYtjoNJ2EjSVeTcKgJ+6vFF",
	"p/7IoJ/K4snvMoFebawiWNXDqpgz7bkpXqT0bq3DXBkzrI9o2lWH/NiM6OmP65QcbkgXpbI72R2hlojJ",
	"rezs5t6swlSB5aET6FPEBrH8JxGv8xlaZCmolIaOejpcKvuPSuV4MvJJ5clsOD+Nz2AQ9fF4fjw7hVF8",
	"Ep3h4Www78M4HkWnszN8Mj9Wfw9nA9yfh3AWn0Yns2M8bgjleDAcnWyXynFTKkePSGX/VIr67mLJgZsd",
	"phRMK6pPIZXDjVI50FJ5qqWyP9BiOdZiOdRi2T9ALCWPeuXSy/phDd7+yXgD849OT0rm16w5QW9BfMfR",
	"LCeJiVCQ5/8dZaE8QW+vqdKmiG1TxLYpYttUBm2K2DZFbJsito2Wb1PEfr0pYpvl1gpzoJgP8VwJ0DxP",
	"EsVUg3Cwp8OjrONRbLzlseq8WDabzPXw09QgqBcdacy9taBEMDYRcabwx+nYMZ3dgg6ScNaCmdpw8xKn",
	"V9a4cQ2bLz8nVjGrzr8dr0ENscE2xNx/N5eKq+KVyKlt8YU+qU3rZdXGNrz6YRWv4814PeWRpq1r85vV",
	"tdmikrggSVLhvYdOMApHh2gjudo0E1NtKfq5nGaisCQ9NVPfZeUS60cJ6mpKuPVj37xwSqN6Jq5WF/fM",
	"2/TT7VQcNufANuH3gQPbATc5xEa8qsV9LYK1WV3kGpMehFhb6vVbLvV6Cfrmz+ETKeD9fe9X5hmbkTgG",
	"OtWmf21vtl9Njnpk6/x/2ebcrLwPktUogdhOJDJza2iKRCFmEHZEqAF7oyRdcL5hNGVrKF1khgh89edG",
	"4dDZIk2EcKV6eEnoZhlta1B/Oc0GDZrZWzUUZ6CVoAoIItQUo3Ytel+98eoXh2CqorfrYYqyPInVDDP5",
	"hXF1DmvSaiA3PB+t5GjTnDLA0ULKdpVY6hzgfH0CaoUNajnOsQo6albJcyquc6gVBMJCQLoUrrJu4NAk",
	"3Csd4SQy7a1TRJy4Aebl3U+TeF7SPaER1taI/J1rRG6xzBzRsOE06mLHDSH96ePDx457nQbCc78t8K26",
	"9CmiIz7KQTcGahzBCoynzhuvcaX0cPdKSr2KnuRFdKSKomCAE7VjlaBY4xLlS7mf8Z6Jhir6ccEAp1w9",
	"xbeNdORftdihHainYiw2xn9osNookB2iQH67oI7OhqjcWkR1EYKs4mxLRfhIzOtmuPYPLhFwLzTXdzUj",
	"1q0frZ1Ui+q2pEKDlTLSH4v9KFD/nkgNIznjhsZY4An6fOPq5Jtggm52MoZugg66MapG97IDqw+F6ai/",
	"+Sz9m+Dhht5QA5aVIwcueaLW3StOED1B0T6YoMFY/mKUr+7h9c30er0doRvXoFMUfXqSaY2qf9dTqJ/r",
	"m7ZuUMGvGZqxG2ZDQ3fXRTAt1WuVjwolCVZ7/Sa8FP61eGkrdNJOlcAtRJo0gRuHDeAudIeK3bw7bKc1",
	"2CQg08Ip7IVQ3RnZZW6CeKxANFfH8ofPN5VrJj2IujiyMIrE4FL1od8ED7vg0N9r9WtOuSb8J831L33X",
	"qs/O1O0P9qeunGELdc881K1e/8gf+wqH6mWb/P10N4KOamD7IH4iOS+H3o2iY6u9Hrbtr80X8lcvjUGn",
	"wnjrttsmk9Z5z+Oza7eYlY6Ne2lb1YxcHU6yzLjPoFWxxRxhZfOrF15mhh66dq1PEy7OG69R3Bci7rsU",
	"BPeC4eJD7YnKs9f97utj9cDirarvZ+d5ZpnsyHLVkXvl+nzz85SGUWxiuXXQxF/GGv7YsWXDv8/i9UGh",
	"xPdTTgT4gojv0R3M5EdvtKJT/7FS8dE+ZHULNOrfmlUV9e9FEcTj8GFrYFkngChLU2AReIB+2bUf0e8J",
	"9Gj8sCEytMsX2bIAncIdnxqCVgF/B3f8IFLPccIPBXvYpLWEsLeOsnRGKBYZK0DnRKIzNffEjjGnflfK",
	"5Lck9sP2yNstbqG2Rmlbo/RrqlFabWV4v3am3zt+IopgaULrPPeUZvtARbMvvpLf4WnGtlv5YcgDx/tb",
	"XFE8Gn9vt7MCaj/mdm8rjJAnwbz/BJgf74r5gdHWVQH60PCZaSuosgU9Hs1QiSf25ndw7Mo7zJHpsXNe",
	"h6cLZigFXPPYzslmbFBGNcmD+8LMGGnukrmxC51K6PxGt/kjqm4Gha7+tUrAL4/Y8qgB86RVwuPaqttS",
	"pqoXyK41bVLFuSxaNWhrlnLjyKWCNPa9w7W3es7237yNLJjStvLGMlyb7SzNubohm4G4A6BorDaRYRi6",
	"WbZrl4rlwOWt2KbZi+iIZnRDuGPYhp22YabZOc2hT7KMF1f53eKJi3vT6wuUMfX/KxOSXsdTTujieO0G",
	"e6gAfH0jq1ofjp+KQae3U7tBTlWwexXVH3Ub+2g91gHxG5Z2Aei7nCXfmah5Urx1jx0kN8zq4ntZmUyO",
	"YzodimsbqfItR6p8j+NC3XaRK5wZQ47nQqm+/p6qD+6Xikv17VH1fKw/ea+l/BJykQDmkvhzBnyB1lnO",
	"zC1Wxsz5BN/qsGQrLtX5KxFqvtuwBebIdGkKS39PxefGlXkVoAa5Gn62GW192FNIO12U3ldRETXMfVD4",
	"ND+kmCR6qc2TxC9G3LPYxT6z82JXtLZeHanJcKKTtUmIy5WqI73jcivX4oZtoL/nNuBB2mr/vTnc4F3s",
	"eiaHkwFaG7ESoYyRX/WYhTevvk/sTglnszmIFO0u8S3vEh8oNgwHsbNNSKJ5uVxtF4OzPbeLGJNkPVVE",
	"msJ9BBDXj8svZAtLRtvCK0uvGIAK/NV5hlQXHQDWD0Nj8IIKD0cxXjui4wXClSANQ2EyN4Cp8Mrp8aiM",
	"vLMiNTjbUbtIptlKj0uHq7aSo2w4Qf3Q7vga/5TQXLiRm75pKyZ1lqEU03UxTA8Z1VVsRSjBQmmkCjWO",
	"DyVFq12+Ze3S4CfURT7OfugE4wOO3+aGWAcyT4ulds0T4301sc6NINfGFl3jc3VDZ14VzBJIpVhxwgXv",
	"IJMJ0Cahq1grPsCqzyhQTuF+qR+oajZySidUVnO888nV1NeZ5hSvMEmaQb+2QI+AdJkxzKS6cxtvNNic",
	"yj05jYHdZpJBUywxpZhG4NET0mpHc7gzWsj1XPgAdclzVU63GdQakYatuvnLqxu/uO8V8Wvu9xEucj5s",
	"DfjVWXU3hvb+kKVLBgugnKxsVm2bopqIRZmgk6+5gLSSp1NfnsmV0aX2GjG+RZpPqZ84TivplQ39MXcy",
	"gM/UfZkOubihZX5oO3sKgpFI7vk6JSCYV1Uq927NDvQFDOscxToz9RcnIDP5iqdGV/gVGeGozGtc6K6y",
	"QEhRKcIR7moVcV3ZSBciapYaOilLAY0G3ro8A7dYztBby6YfVkvNjMa+SjC2akutwnB/MDppZLjedOtT",
	"y0096J069zyWUG5hBjddeCTICqZ3GfukvPHDTiCZSZ41f8lmCpJD4Rj3Rn44nMIDBw3cH/cGvpHdZEIq",
	"/fyjO0NZ79KWrmxkaXxwsmg/ypVuvu1tfGl3xEuI1Xv2IixWcimC+wXOzT3PbgQq0C4BcNfbTvejScuu",
	"MqgxVH1h8yUzOSu6NQ3b4XO4a2tKCeyxuv3TMJQ801zdLZbBvgWH2iT8bRL+r6qOEk6S93NlGrWM3DLy",
	"787IB7JdtVPVrGvLV7blK9vylW35yt+7fKV7dHss5ZhsJemgt+GKXhmd7JuJrPnLx80V+Np9vd3X/9DC",
	"gi0Dtgz456yXuKgg0EXv/9VWSvTEDy/9bGU9YPp79XFGaVAZD1uDqf5U9Rc9zzANchUW0VeXwz2d260j",
	"sXUkto7EdptsHYktI7eM3DoSW0di60hsHYmtI7F1JLb7eruvt47ElgFbR2LrSPzWHYkVldCIUv4ecxL5",
	"g5RfO4HETnjylQrjLYOTE7ICanLL+zMP68RKtp1ZSZMbiKWEForMeQDAckoJve3d0A8cYjRbo4xFC1Dl",
	"9jPG0bOEfAL0r3wGjIIA/tw7oEmbDgzxhUoNrtKCm8SZvuDitwbIJwovtk8QYqkZNjlf1UfH71r4C11J",
	"2sltWLoJV2U4qYUh+7QRAiXJzfl3DWr1TLvFPblJpVl4Cj5xlZrUUg3mqGox86MOJmcQ5xHEKMJLHOmc",
	"Vl+f2lrtkKSklp/vcM1ix9tTtWC5XIddT/zxwtFy6V+ES2PAjZz8lb3O6n31Ag+27HbFO5cdX+OU72J2",
	"2/YAx2uVBk6lLkKC4fmcRL0bqnYkrqw6v5lWvuQx55iOPqrrDHHqaG2e4PCNu2oDOj29u3tmuXkHrWx/",
	"QrlQL/M8e+mlRf2JNlOaiamiz6PXmTQTmpJ7XWea51xPd7u48R5TL0b0tDeN3tvMF1jgmcr/UU5mMnb9",
	"/reavscuuy3oLou5Jza+dTp8iL3fGD3Nc6Lf9F74qV0QW3nxD/U+/NUuUNt1/lOv8wY3eLtOX4u/uF2p",
	"r96xWtrtxQFP2+ate3WPE+CfzRG64Xh1mP+iPY98c+eR1npurefWem6t53adWuu5XanWem6tZ68Zi55V",
	"1sDJmPd86y1LcSOw5ZplhzRqyi72FUN7m2n+WEGSLVNV5EK1rdQcmRwd4SXp3cGsa6pPsF4Mq6PPhsYP",
	"R8pKZ0Tio3i8skKVembN0hbNemy1smcPqs6ZwbuhXkw2OLeigrlS4U6xNZsgrlmstyikV5RjXhGMmrWf",
	"y8HK0nvN0fSqlHedmMaOaKs1dEYya/jw8eF/AwAA//+IGptdRhQBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
